#!/bin/bash

# Chemin du fichier authors à générer
AUTHORS_FILE="authors"

# En-tête du fichier
echo "# File @generated by hack/generate-authors.sh. DO NOT EDIT." > $AUTHORS_FILE
echo "# This file lists all contributors to the repository." >> $AUTHORS_FILE
echo "# See hack/generate-authors.sh to make modifications." >> $AUTHORS_FILE
echo "" >> $AUTHORS_FILE

# Extraction des auteurs du dépôt git et ajout dans le fichier
git log --format='%aN <%aE>' | sort | uniq >> $AUTHORS_FILE
